project_id = "zbjmnnlojxprlogbnxef"

[functions.create-user]
verify_jwt = false

[functions.calcola-provvigioni]
verify_jwt = false

[functions.gestione-rimessa]
verify_jwt = false

[functions.incrocio-bancario]
verify_jwt = false

[functions.gestione-sinistri]
verify_jwt = false

[functions.parse-bank-document]
verify_jwt = false

[functions.match-bank-rows]
verify_jwt = false

[functions.seed-users]
verify_jwt = false
