// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbjmnnlojxprlogbnxef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpiam1ubmxvanhwcmxvZ2JueGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MTQ3ODcsImV4cCI6MjA4NzQ5MDc4N30.ygaCHZGjgBeuiriMoAI8hofqxuaYruJAL9L1TcLZFJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});